image: ruby:3.3

stages:
  - lint
  - test

variables:
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/ImageMagick-6/pkgconfig:/usr/lib/x86_64-linux-gnu/ImageMagick-7/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

.setup:
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends imagemagick libmagickwand-dev fonts-dejavu-core pkg-config
    - gem install bundler
    - bundle install

rubocop:
  stage: lint
  extends: .setup
  script:
    - bundle exec rubocop

rspec:
  stage: test
  extends: .setup
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  coverage: '/\d+\.\d+% covered/'
